name: string_stats
description: string_stats provides utility functions and classes for determining basic frequency statistics on strings. Provides support for asynchronous or incremental accumulation.
version: 0.0.2+1
homepage: https://github.com/ALMaclaine/dart_string_stats
repository: https://github.com/ALMaclaine/dart_string_stats

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  test: ^1.6.0
  effective_dart: ^1.2.1
